# Generated by Django 2.2.5 on 2020-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentSomething',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('SellerName', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('cost', models.IntegerField()),
                ('address', models.CharField(choices=[('Ramanujan', 'Ramanujan'), ('Bhabha', 'Bhabha'), ('Raman', 'Raman'), ('Bose', 'Bose')], default='Ramanujan', max_length=20)),
                ('roomNum', models.IntegerField(max_length=3)),
                ('mobileNum', models.CharField(max_length=10)),
            ],
        ),
    ]
