# Generated by Django 2.2.5 on 2020-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsomething',
            name='roomNum',
            field=models.IntegerField(),
        ),
    ]
