# Generated by Django 2.2.5 on 2020-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0002_auto_20200228_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsomething',
            name='cost',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='rentsomething',
            name='roomNum',
            field=models.CharField(max_length=3),
        ),
    ]
